version: '3'

services:
  sview:
    build: .
    ports:
      - "7676:7676"
    volumes:
      - svcache:/usr/src/app/server/cache
    depends_on:
      - pgdb
    networks:
      - internal
    restart: unless-stopped


  pgdb:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      internal:
        aliases:
          - postgres
    restart: unless-stopped
  
volumes:
  pgdata:
  svcache:

networks:
  internal:
