version: '3'

services:
  sview:
    build: .
    ports:
      - "7676:7676"
    volumes:
      - svcache:/usr/src/app/server/cache
    depends_on:
      - pgdb
    networks:
      - internal


  pgdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      internal:
        aliases:
          - postgres
  
volumes:
  pgdata:
  svcache:

networks:
  internal:
